### ISSUE TITLE
Unable to restore JSON file

### ISSUE THREAD

**Issue by jch02140** [javierbyte/brutalita#3]
Hi,

I have found another bug where after saving the font as a JSON file. When I try to import the JSON the next time I loaded the website, the editor just simply asks for the JSON file but nothing changes or updates in the editor itself.

**Comment by javierbyte** [comment]
@jch02140 do you mind sharing you JSON file? Earlier in development I saw that sometimes I had to upload it twice to get the changes but thought I fixed that issue, maybe you can try?

**Comment by jch02140** [comment]
Hi... I have uploaded a test JSON file generated by the editor here

https://pastebin.com/WCk7bHLT

It is weird... Sometimes, it works after uploading it once... some other times I have to upload it twice to make it works just like you mentioned...

**Comment by javierbyte** [comment]
@jch02140 I made some changes to the restore json functionality, it should work from the first try every time now, please let me know if you can test it :)

**Comment by jch02140** [comment]
It seems to work perfectly now. :) Thanks for the quick fix.
